### ISSUE TITLE
Request for help - interpreting results

### ISSUE THREAD

**Issue by JanaMuschinski** [rkuiper/nopaco#1]
Just started use the package - everything runs fine but I'm having some difficulty understanding interpretation. 

I was previously using the irr package - icc(x, model = "twoway", type = "agreement", unit = "average"), but have realised that for each observer, the scores they have given to the different samples are not normally distributed. From my understanding, irr package's ICC requires normality, so I shouldn't use it. 

We have 11 raters  and 30 samples, with almost all raters rating each sample. Samples are rated on a scale from 1-15. We want to figure out if inter-observer reliability (absolute agreement in this case) is high enough to keep the measure in further hypothesis testing. 

I've done concordance testing for each, but am not sure how to interpret results. I am doing this for 9 difference matrices as I want to know which of the 9 measures aren't reliable across raters and need to be discarded before further analysis. I know as with ICC it's a bit of an arbitrary cut-off, but I wanted to ask if there are generally accepted guidelines, as there sort of are for ICC?

**Comment by rkuiper** [comment]
The icc and nopaco outcomes  are reported on different scales. 

-	Non-parametric concordance is defined in terms of triplets of measurements: a pair of replicate measurements drawn from the same subject and a third measurement from an unrelated subject is discordant if the third measurement falls between the paired measurements. The coefficient 𝜓̄ is then defined as the complement of the ratio between the number of discordant triplets Δ in the data and the total number of triplets 𝜔:  𝜓̄ = 1 – Δ/𝜔, such that in case of no concordance, E(𝜓̄) = 2/3, in contrast E[ICC] = 0. 
-	This relation is explained in Rothery’s paper (Biometrika, 66, 3, 629-639 (1979)) in which a relation is given to ‘translate’ the 𝜓̄ (or Rho_c) into ICC, which might be of interest in the interpretation of 𝜓̄. 

 
 The conversion has been coded in the nopaco function psiFromR
`
>library("nopaco")
>library("tibble")
> icc<-seq(0.5,1.0,0.05)
> tibble(icc,nopaco=nopaco::psifromR(icc)) ##example
\# A tibble: 11 × 2
     icc nopaco
   \<dbl\>  \<dbl\>
  0.5   0.770
  0.55  0.782
  0.6   0.795
  0.65  0.809
  0.7   0.823
  0.75  0.839
  0.8   0.856
  0.85  0.876
  0.9   0.899
  0.95  0.929
  1     1`

**Comment by rkuiper** [comment]
Dear Jana,

 

Sorry for my late response.

 

The icc and nopaco outcomes  are reported on different scales. 

 

*	Non-parametric concordance is defined in terms of triplets of measurements: a pair of replicate measurements drawn from the same subject and a third measurement from an unrelated subject is discordant if the third measurement falls between the paired measurements. The coefficient 𝜓̄ is then defined as the complement of the ratio between the number of discordant triplets Δ in the data and the total number of triplets 𝜔:  𝜓̄ = 1 – Δ/𝜔, such that in case of no concordance, E(𝜓̄) = 2/3, in contrast E[ICC] = 0. 
*	This relation is explained in Rothery’s paper (1979, see snapshot below) in which a relation is given to ‘translate’ the 𝜓̄ (or Rho_c) into ICC, which might be of interest in the interpretation of 𝜓̄. 

 

 



 

 

The convertion has been coded in the nopaco function psiFromR

 

>library("nopaco")

>library("tibble")

> icc<-seq(0.5,1.0,0.05)

> tibble(icc,nopaco=nopaco::psifromR(icc)) ##example

# A tibble: 11 × 2

     icc nopaco

   <dbl>  <dbl>

  0.5   0.770

  0.55  0.782

  0.6   0.795

  0.65  0.809

  0.7   0.823

  0.75  0.839

  0.8   0.856

  0.85  0.876

  0.9   0.899

  0.95  0.929

  1     1

 

I hope this can guide you for further interpretation.

 

Kind regards, 

Rowan Kuiper

 

 

From: Jana Muschinski ***@***.***> 
Sent: Thursday, September 15, 2022 1:06 PM
To: rkuiper/nopaco ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rkuiper/nopaco] Request for help - interpreting results (Issue #1)

 

Just started use the package - everything runs fine but I'm having some difficulty understanding interpretation.

I was previously using the irr package - icc(x, model = "twoway", type = "agreement", unit = "average"), but have realised that for each observer, the scores they have given to the different samples are not normally distributed. From my understanding, irr package's ICC requires normality, so I shouldn't use it.

We have 11 raters and 30 samples, with almost all raters rating each sample. Samples are rated on a scale from 1-15. We want to figure out if inter-observer reliability (absolute agreement in this case) is high enough to keep the measure in further hypothesis testing.

I've done concordance testing for each, but am not sure how to interpret results. I am doing this for 9 difference matrices as I want to know which of the 9 measures aren't reliable across raters and need to be discarded before further analysis. I know as with ICC it's a bit of an arbitrary cut-off, but I wanted to ask if there are generally accepted guidelines, as there sort of are for ICC?

**Comment by JanaMuschinski** [comment]
Thank you, that's a big help!!
